apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: python-app-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: jaysuzi5/python-app