name: ci

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=${GITHUB_SHA::6}" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: jaysuzi5/python-app:${{ env.SHORT_SHA }}
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - name: Install argocd
        shell: bash
        run: |
          curl -ksSl -o argocd-linux-amd64 https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          mv ./argocd /usr/local/bin/argocd
      - name: Argocd app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure \
            --grpc-web \
            --username admin \
            --password ${{ secrets.ARGOCD_TOKEN }}
          argocd app sync python-app